name: Lint and Test and Deploy Project
on: push
jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lints
        run: npm lint
      - name: Run tests
        run: npm test
      - name: Build
        run: npm build
      - name: Deploy
        run: echo "Deploying..."
